// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/middlewareApi/middlewareApi.proto

package middlewareApi

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for MiddlewareApi service

func NewMiddlewareApiEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for MiddlewareApi service

type MiddlewareApiService interface {
	// 中间件操作API
	AddMiddleware(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	DeleteMiddleware(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	UpdateMiddleware(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	FindMiddlewareByID(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	FindAllMiddlewareByTypeID(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 中间件类型API
	AddMiddleType(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	DeleteMiddleType(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	UpdateMiddleType(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	FindMiddleTypeByID(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	FindAllMiddleType(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type middlewareApiService struct {
	c    client.Client
	name string
}

func NewMiddlewareApiService(name string, c client.Client) MiddlewareApiService {
	return &middlewareApiService{
		c:    c,
		name: name,
	}
}

func (c *middlewareApiService) AddMiddleware(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MiddlewareApi.AddMiddleware", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middlewareApiService) DeleteMiddleware(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MiddlewareApi.DeleteMiddleware", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middlewareApiService) UpdateMiddleware(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MiddlewareApi.UpdateMiddleware", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middlewareApiService) FindMiddlewareByID(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MiddlewareApi.FindMiddlewareByID", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middlewareApiService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MiddlewareApi.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middlewareApiService) FindAllMiddlewareByTypeID(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MiddlewareApi.FindAllMiddlewareByTypeID", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middlewareApiService) AddMiddleType(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MiddlewareApi.AddMiddleType", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middlewareApiService) DeleteMiddleType(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MiddlewareApi.DeleteMiddleType", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middlewareApiService) UpdateMiddleType(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MiddlewareApi.UpdateMiddleType", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middlewareApiService) FindMiddleTypeByID(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MiddlewareApi.FindMiddleTypeByID", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middlewareApiService) FindAllMiddleType(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MiddlewareApi.FindAllMiddleType", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MiddlewareApi service

type MiddlewareApiHandler interface {
	// 中间件操作API
	AddMiddleware(context.Context, *Request, *Response) error
	DeleteMiddleware(context.Context, *Request, *Response) error
	UpdateMiddleware(context.Context, *Request, *Response) error
	FindMiddlewareByID(context.Context, *Request, *Response) error
	Call(context.Context, *Request, *Response) error
	FindAllMiddlewareByTypeID(context.Context, *Request, *Response) error
	// 中间件类型API
	AddMiddleType(context.Context, *Request, *Response) error
	DeleteMiddleType(context.Context, *Request, *Response) error
	UpdateMiddleType(context.Context, *Request, *Response) error
	FindMiddleTypeByID(context.Context, *Request, *Response) error
	FindAllMiddleType(context.Context, *Request, *Response) error
}

func RegisterMiddlewareApiHandler(s server.Server, hdlr MiddlewareApiHandler, opts ...server.HandlerOption) error {
	type middlewareApi interface {
		AddMiddleware(ctx context.Context, in *Request, out *Response) error
		DeleteMiddleware(ctx context.Context, in *Request, out *Response) error
		UpdateMiddleware(ctx context.Context, in *Request, out *Response) error
		FindMiddlewareByID(ctx context.Context, in *Request, out *Response) error
		Call(ctx context.Context, in *Request, out *Response) error
		FindAllMiddlewareByTypeID(ctx context.Context, in *Request, out *Response) error
		AddMiddleType(ctx context.Context, in *Request, out *Response) error
		DeleteMiddleType(ctx context.Context, in *Request, out *Response) error
		UpdateMiddleType(ctx context.Context, in *Request, out *Response) error
		FindMiddleTypeByID(ctx context.Context, in *Request, out *Response) error
		FindAllMiddleType(ctx context.Context, in *Request, out *Response) error
	}
	type MiddlewareApi struct {
		middlewareApi
	}
	h := &middlewareApiHandler{hdlr}
	return s.Handle(s.NewHandler(&MiddlewareApi{h}, opts...))
}

type middlewareApiHandler struct {
	MiddlewareApiHandler
}

func (h *middlewareApiHandler) AddMiddleware(ctx context.Context, in *Request, out *Response) error {
	return h.MiddlewareApiHandler.AddMiddleware(ctx, in, out)
}

func (h *middlewareApiHandler) DeleteMiddleware(ctx context.Context, in *Request, out *Response) error {
	return h.MiddlewareApiHandler.DeleteMiddleware(ctx, in, out)
}

func (h *middlewareApiHandler) UpdateMiddleware(ctx context.Context, in *Request, out *Response) error {
	return h.MiddlewareApiHandler.UpdateMiddleware(ctx, in, out)
}

func (h *middlewareApiHandler) FindMiddlewareByID(ctx context.Context, in *Request, out *Response) error {
	return h.MiddlewareApiHandler.FindMiddlewareByID(ctx, in, out)
}

func (h *middlewareApiHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.MiddlewareApiHandler.Call(ctx, in, out)
}

func (h *middlewareApiHandler) FindAllMiddlewareByTypeID(ctx context.Context, in *Request, out *Response) error {
	return h.MiddlewareApiHandler.FindAllMiddlewareByTypeID(ctx, in, out)
}

func (h *middlewareApiHandler) AddMiddleType(ctx context.Context, in *Request, out *Response) error {
	return h.MiddlewareApiHandler.AddMiddleType(ctx, in, out)
}

func (h *middlewareApiHandler) DeleteMiddleType(ctx context.Context, in *Request, out *Response) error {
	return h.MiddlewareApiHandler.DeleteMiddleType(ctx, in, out)
}

func (h *middlewareApiHandler) UpdateMiddleType(ctx context.Context, in *Request, out *Response) error {
	return h.MiddlewareApiHandler.UpdateMiddleType(ctx, in, out)
}

func (h *middlewareApiHandler) FindMiddleTypeByID(ctx context.Context, in *Request, out *Response) error {
	return h.MiddlewareApiHandler.FindMiddleTypeByID(ctx, in, out)
}

func (h *middlewareApiHandler) FindAllMiddleType(ctx context.Context, in *Request, out *Response) error {
	return h.MiddlewareApiHandler.FindAllMiddleType(ctx, in, out)
}
